// <auto-generated />
using System;
using Fiap.banco.api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.banco.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408015146_CriarTabelasFuncionario")]
    partial class CriarTabelasFuncionario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.banco.api.Model.Banco", b =>
                {
                    b.Property<int>("idBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idBanco"));

                    b.Property<DateTime>("dtCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("nomeBanco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idBanco");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("Fiap.banco.api.Model.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("BancoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id");

                    b.HasIndex("BancoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Fiap.banco.api.Model.Funcionario", b =>
                {
                    b.Property<int>("idFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFuncionario"));

                    b.HasKey("idFuncionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Fiap.banco.api.Model.Cliente", b =>
                {
                    b.HasOne("Fiap.banco.api.Model.Banco", "Banco")
                        .WithMany("Clientes")
                        .HasForeignKey("BancoId");

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("Fiap.banco.api.Model.Banco", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
